spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql:3306/master_database?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

server:
  port: 8081
  servlet:
    context-path: /api

eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@discovery-service:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

