spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://mysql:3306/master_database?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false

server:
  port: 8081
  servlet:
    context-path: /api
